on:
    push:
        branches: [main]

name: "Docker build"
permissions:
    contents: read
    pull-requests: write
defaults:
  run:
    working-directory: './'
jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - name: Clone Repo
              uses: actions/checkout@v3
            - name: Podman test
              run: which podman
            - name: Pull UBI 9 Image
              run: docker pull registry.access.redhat.com/ubi9/ubi@sha256:ed84f34cd929ea6b0c247b6daef54dd79602804a32480a052951021caf429494
            - name: Build UBI 9 Image
              run: docker build -t ubi9/conor-ubi:9.0.0 .
            - name: Tag custom UBI 9 Image
              run: docker tag ubi9/conor-ubi:9.0.0 ghcr.io/ubi/conor-ubi:9.0.0
            - name: Push UBI 9 Image
              if: github.actor == 'conor-ubi[bot]'
              run: |
                echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
                docker push ghcr.io/conor/conor-ubi:9.0.0
    CISBench:
        runs-on: ubuntu-latest
        steps:
            - name: Push UBI 9 Image
              if: github.actor == 'conor-ubi[bot]'
              run: |
                echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
                docker pull ghcr.io/conor/conor-ubi:9.0.0
            - name: Setup docker bench
              run: |
                git clone https://github.com/docker/docker-bench-security.git
                cd docker-bench-security
                docker build --no-cache -t docker-bench-security .
            - name: Run docker bench
              run: |
                docker run --rm --net host --pid host --userns host --cap-add audit_control \
                  -e DOCKER_CONTENT_TRUST=$DOCKER_CONTENT_TRUST \
                  -v /etc:/etc:ro \
                  -v /lib/systemd/system:/lib/systemd/system:ro \
                  -v /usr/bin/containerd:/usr/bin/containerd:ro \
                  -v /usr/bin/runc:/usr/bin/runc:ro \
                  -v /usr/lib/systemd:/usr/lib/systemd:ro \
                  -v /var/lib:/var/lib:ro \
                  -v /var/run/docker.sock:/var/run/docker.sock:ro \
                  --label docker_bench_security \
                  docker-bench-security
        
