on:
    push:
        branches: [main]

name: "Docker build"
permissions:
    contents: read
    pull-requests: write
    packages: write
defaults:
  run:
    working-directory: './'
env: 
  DOCKER_IMAGE: "ghcr.io/conor/conor-ubi:9.0.0"
jobs:
    Build-Image:
        runs-on: ubuntu-latest
        steps:
            - name: Clone Repo
              uses: actions/checkout@v3
            - name: Podman test
              run: which podman
            - name: Pull UBI 9 Image
              run: docker pull registry.access.redhat.com/ubi9/ubi@sha256:ed84f34cd929ea6b0c247b6daef54dd79602804a32480a052951021caf429494
            - name: Build and tag custom UBI 9 Image
              run: docker build -t ${{ env.DOCKER_IMAGE }} .
            - name: List Images
              run: docker images --filter=reference="${{ env.DOCKER_IMAGE }}"
            - name: Push UBI 9 Image
              run: |
                echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
                docker push ${{ env.DOCKER_IMAGE }}
    CIS-Bench:
        runs-on: ubuntu-latest
        needs: Build-Image
        steps:
            - name: Pull Base image
              run: |
                echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
                docker pull  ${{ env.DOCKER_IMAGE }}
            - name: Setup docker bench
              run: |
                git clone https://github.com/docker/docker-bench-security.git
                cd docker-bench-security
                docker build --no-cache -t docker-bench-security .
            - name: Run Base images
              run: |
                docker run ${{ env.DOCKER_IMAGE }} -d
            - name: Run docker bench
              run: |
                docker run --rm --net host --pid host --userns host --cap-add audit_control \
                  -e DOCKER_CONTENT_TRUST=$DOCKER_CONTENT_TRUST \
                  -v /etc:/etc:ro \
                  -v /lib/systemd/system:/lib/systemd/system:ro \
                  -v /usr/bin/containerd:/usr/bin/containerd:ro \
                  -v /usr/bin/runc:/usr/bin/runc:ro \
                  -v /usr/lib/systemd:/usr/lib/systemd:ro \
                  -v /var/lib:/var/lib:ro \
                  -v /var/run/docker.sock:/var/run/docker.sock:ro \
                  --label docker_bench_security \
                  docker-bench-security -i ${{ env.DOCKER_IMAGE }} -c container_images
        
